name: Javascript Playwright Tests

# Déclenche sur push ou pull request sur toutes les branches
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  schedule:
    -cron: '*/5 * * * *'
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'   # ou une autre version LTS

      - name: Install dependencies
        run: npm ci   # installe les dépendances selon package-lock.json

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: npm test

