name: Daily Playwright Tests

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'     # Exécution tous les jours à 6h UTC
  workflow_dispatch:        # Permet de lancer manuellement depuis GitHub

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-html
        playwright install --with-deps

    - name: Run Playwright tests
      run: |
        pytest tests/ --html=rapport.html

    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      with:
        name: rapport-playwright
        path: rapport.html

